version: "3"
services:
  app:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
  mariadb:
    image: mariadb:latest
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret