version: "3"
services:
  app:
    build: .
    depends_on:
      - mariadb
    ports:
      - 8080:80
    volumes:
      - .:/srv/app
  mariadb:
    image: mariadb:latest
    ports:
      - 33060:3306
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
volumes:
   mariadb:
    driver: local
